rules:
  indent:
    - 2
    - 4
  linebreak-style:
    - 2
    - unix
env:
  es6: true
  browser: true
  node: true
extends: 'eslint:recommended'
ecmaFeatures:
  jsx: true
  modules: true
  experimentalObjectRestSpread: true
plugins:
  - react
globals:
    describe: true
    it: true
    before: true
    after: true
    beforeEach: true
    afterEach: true